import PitchDeck from "./PitchDeck";
import LinkGate from "./LinkGate";
import { verifyPitchToken } from "@/lib/pitch-link";
import { getAdminSession } from "@/lib/admin-auth";

/**
 * Operator pitch deck. Hidden + noindex (see layout.tsx) AND access-gated:
 * every send requires a signed, expiring link token (`?t=`) generated by the
 * sales team from /admin/pitch-links. The operator name (watermark) is read
 * from the token, so a recipient can't edit or strip it.
 *
 * Logged-in admins may open /pitch without a token to preview the deck.
 */
export default async function PitchPage({
  searchParams,
}: {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}) {
  const sp = await searchParams;
  const token = typeof sp.t === "string" ? sp.t : null;

  const verified = await verifyPitchToken(token);
  if (verified) {
    // Best-effort open log (visible in Vercel function logs). A durable
    // per-link open store (Upstash) can hang off this later.
    console.log(
      `[pitch] open operator=${JSON.stringify(verified.operator)} sentBy=${JSON.stringify(verified.sentBy)}`,
    );
    return <PitchDeck operator={verified.operator.slice(0, 60)} />;
  }

  // No / invalid / expired token: only a logged-in admin may preview.
  const admin = await getAdminSession();
  if (admin) {
    const raw = sp.o;
    const previewName =
      typeof raw === "string" && raw.trim() ? raw.trim().slice(0, 60) : "PREVIEW";
    return <PitchDeck operator={previewName} />;
  }

  return <LinkGate />;
}
